feat(github): single image pack (#61)
* feat(github): single image pack

* fix(github): grammar

* feat(github): include prop

* refactor(github): rm check changed step

* refactor(github): include option command

* fix(github): image pack command

* feat(github): exclude optional step

* feat(github): validate inputs

diff --git a/.github/workflows/pack-image.yaml b/.github/workflows/pack-image.yaml
--- a/.github/workflows/pack-image.yaml
+++ b/.github/workflows/pack-image.yaml
@@ -29,6 +29,14 @@ on:
         default: true
         type: boolean
         description: 'Login via echo -e. Default: true'
+      include:
+        required: false
+        type: string
+        description: 'A comma-separated list of workspace names or glob patterns to include in the build. If provided, only these packages will be processed.'
+      exclude:
+        required: false
+        type: string
+        description: 'A comma-separated list of workspace names or glob patterns to exclude from the build. If provided, these packages will be skipped.'
     secrets:
       registryKey:
         required: true
@@ -41,6 +49,12 @@ jobs:
   run:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate inputs - include and exclude
+        if: ${{ inputs.include && inputs.exclude }}
+        run: |
+          echo "Error: You cannot specify both 'include' and 'exclude' at the same time."
+          exit 1
+
       - name: Login to registry
         env:
           REGISTRY_KEY: ${{ secrets.registryKey }}
@@ -52,8 +66,6 @@ jobs:
 
       - name: Checkout
         uses: actions/checkout@v4
-        with:
-          ref: master
 
       - name: Setup Node
         uses: actions/setup-node@v4
@@ -80,6 +92,7 @@ jobs:
           (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.36.2/pack-v0.36.2-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
 
       - name: Pack and publish
+        if: ${{ !inputs.include && !inputs.exclude }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REGISTRY_URL: ${{ inputs.registryURL }}
@@ -89,3 +102,39 @@ jobs:
           PROJECT_LOWER=$(echo "$PROJECT" | tr '[:upper:]' '[:lower:]')
 
           yarn workspaces changed foreach -vpj 2 image pack --publish --tag-policy hash-timestamp --registry "$REGISTRY_URL/$PROJECT_LOWER/$IMAGE_NAME_PREFIX"
+
+      - name: Pack and publish included packages
+        if: ${{ inputs.include }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          REGISTRY_URL: ${{ inputs.registryURL }}
+          PROJECT: ${{ secrets.project != '' && secrets.project || inputs.project }}
+          IMAGE_NAME_PREFIX: ${{ inputs.imageNamePrefix }}
+        run: |
+          PROJECT_LOWER=$(echo "$PROJECT" | tr '[:upper:]' '[:lower:]')
+
+          IFS=',' read -r -a include_array <<< "${{ inputs.include }}"
+          INCLUDE_FLAGS=""
+          for ws in "${include_array[@]}"; do
+            INCLUDE_FLAGS+="--include \"$ws\" "
+          done
+
+          yarn workspaces foreach --all $INCLUDE_FLAGS image pack --publish --tag-policy hash-timestamp --registry "$REGISTRY_URL/$PROJECT_LOWER/$IMAGE_NAME_PREFIX"
+
+      - name: Pack and publish without excluded
+        if: ${{ !inputs.include && inputs.exclude }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          REGISTRY_URL: ${{ inputs.registryURL }}
+          PROJECT: ${{ secrets.project != '' && secrets.project || inputs.project }}
+          IMAGE_NAME_PREFIX: ${{ inputs.imageNamePrefix }}
+        run: |
+          PROJECT_LOWER=$(echo "$PROJECT" | tr '[:upper:]' '[:lower:]')
+
+          IFS=',' read -r -a include_array <<< "${{ inputs.exclude }}"
+          EXCLUDE_FLAGS=""
+          for ws in "${include_array[@]}"; do
+            EXCLUDE_FLAGS+="--exclude \"$ws\" "
+          done
+
+          yarn workspaces foreach --all $EXCLUDE_FLAGS image pack --publish --tag-policy hash-timestamp --registry "$REGISTRY_URL/$PROJECT_LOWER/$IMAGE_NAME_PREFIX"
